apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: cert-manager
        namespace: cert-manager
  template:
    metadata:
      name: '{{app}}'
      labels:
        app: '{{app}}'
    spec:
      project: default
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: 1.19.2
        helm:
          values: |
            installCRDs: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
