{{- if .Values.instrumentation.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "diiage-finals-app.fullname" . }}-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: {{ .Values.instrumentation.exporterEndpoint }}
  
  propagators:
    - tracecontext
    - baggage
    - b3
  
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  
  env:
    - name: OTEL_SERVICE_NAME
      value: {{ .Values.instrumentation.serviceName | default "backend" | quote }}
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: {{ .Values.instrumentation.exporterEndpoint | quote }}
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name={{ .Values.instrumentation.serviceName | default "backend" }},service.namespace={{ .Release.Namespace }}"
{{- end }}
