{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "diiage-finals-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "diiage-finals-app.labels" . | nindent 4 }}
    app: {{ include "diiage-finals-app.name" . }}-backend
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end }}
