{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diiage-finals-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "diiage-finals-app.labels" . | nindent 4 }}
    app: {{ include "diiage-finals-app.name" . }}-backend
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
